# Site settings
title: A website about Gem Pack Co,.Ltd.
description: A website about Gem Pack Co,.Ltd.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gem Pack Co.,Ltd.
user_description: The company started in 2018. We want to make a lot of Funny Games. Now we are making puzzle game mixed RPG. We'll a leading and exemplary development company.
user_title: Funny Game Develop Company
email: contact@gempack.co.kr
twitter_username: ejunghyun
github_username:  gempack
gplus_username:  ejunghyun

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
